// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyccsodxtucpmmjphdrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Y2Nzb2R4dHVjcG1tanBoZHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDU2MDIsImV4cCI6MjA1ODQyMTYwMn0.SkvLqrWLaFyWrbo3OzE4GI22prEwmaqrTw0GJ72RWUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);